# Generated by Django 4.2.7 on 2023-12-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagapp', '0002_newarrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagapp.category')),
            ],
        ),
    ]
