# Generated by Django 4.2.7 on 2023-12-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagapp', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
